package kemahasiswaan_10116514_10116517;
import javax.swing.*;
//Fungsi import untuk SQL
import java.sql.*;
//Fungsi import untuk tanggal
import java.text.SimpleDateFormat;
import java.util.Date;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahasiswa
 */
public class frm_mhs extends javax.swing.JFrame {
//deklarasi variable
koneksi dbsetting;
String driver,database,user,pass;
Object tabel;

    /**
     * Creates new form frm_mhs
     */
    public frm_mhs() {
        initComponents();
        
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        tabel_mahasiswa.setModel(tableModel);
        
        settableload();
    }
    
    private javax.swing.table.DefaultTableModel tableModel=getDefaultTableModel();
    private javax.swing.table.DefaultTableModel getDefaultTableModel()
    {
     //membuat judul header
     return new javax.swing.table.DefaultTableModel
     (
          new Object [] [] {},
          new String [] {"NIM",
                         "Nama Mahasiswa",
                         "Tempat Lahir",
                         "Tanggal Lahir",
                         "Alamat"}
     )
     // disable perubahan pada grid
     {
         boolean[] canEdit = new boolean[]
         {
             false, false, false, false, false
         };
         
         public boolean isCellEditable(int rowIndex, int columnIndex)
         {
             return canEdit[columnIndex];
         }
     };
        
    }
    
    String data[] = new String[5];
    private void settableload()
    {
        String stat = "";
        try
        {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            
            Statement stt=kon.createStatement();
            String SQL = "select * from t_mahasiswa order by nim asc";
            ResultSet res = stt.executeQuery(SQL);
            while (res.next())
            {
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                data[3] = res.getString(4);
                data[4] = res.getString(5);
                tableModel.addRow(data);
            }
            res.close();
            stt.close();
            kon.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
            
            System.exit(0);
        }
    }
    
    public void membersihkan_teks()
    {
        tempat_nim.setText("");
        tempat_nama.setText("");
        tempat_tgl.setText("");
        tempat_lahir.setText("");
        tempat_alamat.setText("");
        tempat_cari.setText("");
     
    }
    public void nonaktifkan_teks()
    {
        tempat_nim.setEnabled(false);
        tempat_nama.setEnabled(false);;
        tempat_tgl.setEnabled(false);
        tempat_lahir.setEnabled(false);
        tempat_alamat.setEnabled(false);
    }
    public void aktif_teks()
    {
        tempat_nim.setEnabled(true);
        tempat_nama.setEnabled(true);
        tempat_tgl.setEnabled(true);
        tempat_lahir.setEnabled(true);
        tempat_alamat.setEnabled(true);
    }
    
    int row = 0;
    public void tampil_field()
    {
        row = tabel_mahasiswa.getSelectedRow();
        tempat_nim.setText(tableModel.getValueAt(row, 0).toString());
        tempat_nama.setText(tableModel.getValueAt(row, 1).toString());
        tempat_lahir.setText(tableModel.getValueAt(row, 2).toString());
        tempat_tgl.setText(tableModel.getValueAt(row, 3).toString());
        tempat_alamat.setText(tableModel.getValueAt(row, 4).toString());
        save.setEnabled(false);
        change.setEnabled(true);
        delete.setEnabled(true);
        cancel.setEnabled(true);
        aktif_teks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        change = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        out = new javax.swing.JButton();
        tempat_nim = new javax.swing.JTextField();
        tempat_nama = new javax.swing.JTextField();
        tempat_lahir = new javax.swing.JTextField();
        tempat_tgl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_mahasiswa = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tempat_alamat = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tempat_cari = new javax.swing.JTextField();
        searching = new javax.swing.JButton();
        display = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NIM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tempat Lahir");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Tanggal Lahir");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        add.setText("Tambah");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 100, -1));

        change.setText("Ubah");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        getContentPane().add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 100, -1));

        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 90, -1));

        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 90, -1));

        cancel.setText("Batal");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 90, -1));

        out.setText("Keluar");
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });
        getContentPane().add(out, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 90, -1));
        getContentPane().add(tempat_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 68, -1));
        getContentPane().add(tempat_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 188, -1));
        getContentPane().add(tempat_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 188, -1));
        getContentPane().add(tempat_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 98, -1));

        tabel_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_mahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_mahasiswa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 650, 280));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("(yyyy-mm-dd)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        tempat_alamat.setColumns(20);
        tempat_alamat.setRows(5);
        jScrollPane2.setViewportView(tempat_alamat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 250, 60));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Mahasiswa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Pencarian Data Mahasiswa", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Masukkan NIM");

        searching.setText("Cari");
        searching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchingActionPerformed(evt);
            }
        });

        display.setText("Tampilkan Keseluruhan Data");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(tempat_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searching, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(display)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tempat_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searching)
                    .addComponent(display))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 680, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        membersihkan_teks();
        tempat_nim.requestFocus();
        save.setEnabled(true);
        change.setEnabled(false);
        delete.setEnabled(false);
        out.setEnabled(false);
        add.setEnabled(false);
        aktif_teks();
    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String data[]=new String[5];
        
        if ((tempat_nim.getText().isEmpty()) || (tempat_tgl.getText().isEmpty())) 
        {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong,silahkan dilengkapi");
            tempat_nim.requestFocus();
        }
        else if((tempat_tgl.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong,silahkan dilengkapi");
            tempat_tgl.requestFocus();
        }
        else
        {
            try
            {
                Class.forName(driver);
                Connection kon = DriverManager.getConnection(
                                    database,
                                    user,
                                    pass);
                Statement stt = kon.createStatement();
                String SQL = "INSERT INTO t_mahasiswa(nim,"
                             + "nama,"
                             + "tempat_lahir,"
                             + "tgl_lahir,"
                             + "alamat) "
                                + "VALUES "
                            + "( '"+tempat_nim.getText()+"',"
                            +  "'"+tempat_nama.getText()+"',"
                            + "'"+tempat_lahir.getText()+"',"
                            + "'"+tempat_tgl.getText()+"',"
                            + "'"+tempat_alamat.getText()+"')";b
                stt.executeUpdate(SQL);
                data[0] = tempat_nim.getText();
                data[1] = tempat_nama.getText();
                data[2] = tempat_lahir.getText();
                data[3] = tempat_tgl.getText();
                data[4] = tempat_alamat.getText();
                tableModel.insertRow(0, data);
                stt.close();
                kon.close();
                membersihkan_teks();
                save.setEnabled(false);
                nonaktifkan_teks();
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, 
                    ex.getMessage(),"Error",
                    JOptionPane.INFORMATION_MESSAGE
                    );
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void tabel_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_mahasiswaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==1) 
        {
            tampil_field();
        }
    }//GEN-LAST:event_tabel_mahasiswaMouseClicked

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
        String nim=tempat_nim.getText();
        String nama=tempat_nama.getText();
        String tempat_lahiir = tempat_lahir.getText();
        String tanggal_lahir=tempat_tgl.getText();
        String alamat=tempat_alamat.getText();
        
        if ((nim.isEmpty()) | (alamat.isEmpty()))
        {
            JOptionPane.showMessageDialog(null,"data tidak boleh kosong, silahkan dilengkapi");
            tempat_nim.requestFocus();
        }
        else
        {
            try 
            {
                Class.forName(driver);
                Connection kon = DriverManager.getConnection(database,user,pass);
                Statement stt = kon.createStatement();
                String SQL = "UPDATE `t_mahasiswa`"
                        + "SET `nim`='"+nim+"',"
                        + "`nama`='"+nama+"',"
                        + "`tempat_lahir`='"+tempat_lahiir+"',"
                        + "`tgl_lahir`='"+tanggal_lahir+"',"
                        + "`alamat`='"+alamat+"' "
                    + "WHERE "
                    + "`nim`='"+tableModel.getValueAt(row, 0).toString()+"';";
                stt.executeUpdate(SQL);
                data[0] = nim;
                data[1] = nama;
                data[2] = tempat_lahiir;
                data[3] = tanggal_lahir;
                data[4] = alamat;
                tableModel.removeRow(row);
                tableModel.insertRow(row, data);
                
                stt.close();
                kon.close();
                membersihkan_teks();
                save.setEnabled(false);
                nonaktifkan_teks();
            } 
            catch (Exception ex) 
            {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_changeActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try 
        {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            Statement stt = kon.createStatement();
            String SQL = "Delete From t_mahasiswa "
                            + "WHERE "
                          + "nim='"+tableModel.getValueAt(row, 0).toString()+"'";
            stt.executeUpdate(SQL);
            tableModel.removeRow(row);
            stt.close();
            kon.close();
            membersihkan_teks();
        } 
        catch (Exception ex) 
        {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void searchingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchingActionPerformed
        // TODO add your handling code here:
        //menghapus seluruh isi data dalam tabel
        tableModel.setRowCount(0);
        //query untuk cari
        try 
        {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            Statement stt = kon.createStatement();
            String SQL = "SELECT * FROM t_mahasiswa WHERE nim="
                          +tempat_cari.getText();
            ResultSet res = stt.executeQuery(SQL);
            while (res.next()) 
            {
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                data[3] = res.getString(4);
                data[4] = res.getString(5);
                tableModel.addRow(data);
            }
            res.close();
            stt.close();
            kon.close();
        } 
        catch (Exception ex) 
        {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, 
                ex.getMessage(),"Error",
                JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_searchingActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        settableload();
        membersihkan_teks();
    }//GEN-LAST:event_displayActionPerformed

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_outActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        add.setEnabled(true);
        change.setEnabled(true);
        delete.setEnabled(true);
        save.setEnabled(true);
        cancel.setEnabled(true);
        out.setEnabled(true);
        membersihkan_teks();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_mhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JButton change;
    private javax.swing.JButton delete;
    private javax.swing.JButton display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton out;
    private javax.swing.JButton save;
    private javax.swing.JButton searching;
    private javax.swing.JTable tabel_mahasiswa;
    private javax.swing.JTextArea tempat_alamat;
    private javax.swing.JTextField tempat_cari;
    private javax.swing.JTextField tempat_lahir;
    private javax.swing.JTextField tempat_nama;
    private javax.swing.JTextField tempat_nim;
    private javax.swing.JTextField tempat_tgl;
    // End of variables declaration//GEN-END:variables
}
